### ISSUE TITLE
How to use this package?

### ISSUE THREAD

**Issue by mauran** [michaelKaefer/guzzlehttp6-for-prestashop17#1]
Currently tryin to get this to work. My module has the composer.json in it and after installing i still get the errors with guzzle 5/guzzle 6. Is there need to do something extra?

**Comment by michaelKaefer** [comment]
Can you post your code and the error message? It should work without any extra steps.

**Comment by mauran** [comment]
Well not really. I've installed an SDK that uses https://github.com/thephpleague/oauth2-client which uses guzzle 6. Even when i've installed guzzlehttp6-for-prestashop17 i still get some errors about guzzle 5 is retrieved instead of guzzle 6

**Comment by michaelKaefer** [comment]
That is because the package still uses the Guzzle version 5 which is used by PrestaShop. You can replace [https://github.com/thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client) with [https://github.com/michaelKaefer/oauth2client-for-prestashop17](https://github.com/michaelKaefer/oauth2client-for-prestashop17). Which service you want to use (Amazon, PayPal, etc)? It may still not work, better tell me which service you need, maybe I have another package for it. General: it is a real pain. The main problem is PrestaShop uses Guzzle 5 of course..

**Comment by mauran** [comment]
Ah. I see. We wanted to consume our own SDK into Prestashop, but we can see that it's a bigger hazzle than expected. We're currently looking at other solutions. Thanks for the help though :)
